services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: flights-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - flights-network
    pull_policy: missing
    tmpfs:
      - /var/cache/nginx
      - /tmp

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: flights-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - flights-network

  db:
    image: mysql:8.0
    container_name: flights-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flights
    command: 
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/01-dump.sql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/02-security.sql
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - flights-network
    pull_policy: missing

volumes:
  db_data:

networks:
  flights-network:
    driver: bridge
