services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: flights-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - flights-network
    pull_policy: missing
    tmpfs:
      - /var/cache/nginx
      - /tmp

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: flights-php
    restart: always
    environment:
      - MYSQL_APP_USER=${MYSQL_APP_USER}
      - MYSQL_APP_PASSWORD=${MYSQL_APP_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - flights-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: flights-db
    restart: always
    command:
      - --default-authentication-plugin=caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/01-dump.sql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/02-security.sql
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      - MYSQL_APP_USER=${MYSQL_APP_USER}
      - MYSQL_APP_PASSWORD=${MYSQL_APP_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - flights-network
    pull_policy: missing

volumes:
  db_data:

networks:
  flights-network:
    driver: bridge